// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/bike.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fbike_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fbike_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fbike_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fbike_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fbike_2eproto;
namespace bike {
class mobile_code_request;
struct mobile_code_requestDefaultTypeInternal;
extern mobile_code_requestDefaultTypeInternal _mobile_code_request_default_instance_;
class mobile_code_response;
struct mobile_code_responseDefaultTypeInternal;
extern mobile_code_responseDefaultTypeInternal _mobile_code_response_default_instance_;
}  // namespace bike
PROTOBUF_NAMESPACE_OPEN
template<> ::bike::mobile_code_request* Arena::CreateMaybeMessage<::bike::mobile_code_request>(Arena*);
template<> ::bike::mobile_code_response* Arena::CreateMaybeMessage<::bike::mobile_code_response>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bike {

// ===================================================================

class mobile_code_request final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bike.mobile_code_request) */ {
 public:
  inline mobile_code_request() : mobile_code_request(nullptr) {}
  ~mobile_code_request() override;
  explicit PROTOBUF_CONSTEXPR mobile_code_request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  mobile_code_request(const mobile_code_request& from);
  mobile_code_request(mobile_code_request&& from) noexcept
    : mobile_code_request() {
    *this = ::std::move(from);
  }

  inline mobile_code_request& operator=(const mobile_code_request& from) {
    CopyFrom(from);
    return *this;
  }
  inline mobile_code_request& operator=(mobile_code_request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const mobile_code_request& default_instance() {
    return *internal_default_instance();
  }
  static inline const mobile_code_request* internal_default_instance() {
    return reinterpret_cast<const mobile_code_request*>(
               &_mobile_code_request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(mobile_code_request& a, mobile_code_request& b) {
    a.Swap(&b);
  }
  inline void Swap(mobile_code_request* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(mobile_code_request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  mobile_code_request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<mobile_code_request>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const mobile_code_request& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const mobile_code_request& from) {
    mobile_code_request::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(mobile_code_request* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bike.mobile_code_request";
  }
  protected:
  explicit mobile_code_request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMobileFieldNumber = 1,
  };
  // required string mobile = 1;
  bool has_mobile() const;
  private:
  bool _internal_has_mobile() const;
  public:
  void clear_mobile();
  const std::string& mobile() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_mobile(ArgT0&& arg0, ArgT... args);
  std::string* mutable_mobile();
  PROTOBUF_NODISCARD std::string* release_mobile();
  void set_allocated_mobile(std::string* mobile);
  private:
  const std::string& _internal_mobile() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_mobile(const std::string& value);
  std::string* _internal_mutable_mobile();
  public:

  // @@protoc_insertion_point(class_scope:bike.mobile_code_request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mobile_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fbike_2eproto;
};
// -------------------------------------------------------------------

class mobile_code_response final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bike.mobile_code_response) */ {
 public:
  inline mobile_code_response() : mobile_code_response(nullptr) {}
  ~mobile_code_response() override;
  explicit PROTOBUF_CONSTEXPR mobile_code_response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  mobile_code_response(const mobile_code_response& from);
  mobile_code_response(mobile_code_response&& from) noexcept
    : mobile_code_response() {
    *this = ::std::move(from);
  }

  inline mobile_code_response& operator=(const mobile_code_response& from) {
    CopyFrom(from);
    return *this;
  }
  inline mobile_code_response& operator=(mobile_code_response&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const mobile_code_response& default_instance() {
    return *internal_default_instance();
  }
  static inline const mobile_code_response* internal_default_instance() {
    return reinterpret_cast<const mobile_code_response*>(
               &_mobile_code_response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(mobile_code_response& a, mobile_code_response& b) {
    a.Swap(&b);
  }
  inline void Swap(mobile_code_response* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(mobile_code_response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  mobile_code_response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<mobile_code_response>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const mobile_code_response& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const mobile_code_response& from) {
    mobile_code_response::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(mobile_code_response* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bike.mobile_code_response";
  }
  protected:
  explicit mobile_code_response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDescFieldNumber = 3,
    kCodeFieldNumber = 1,
    kIcodeFieldNumber = 2,
  };
  // optional string desc = 3;
  bool has_desc() const;
  private:
  bool _internal_has_desc() const;
  public:
  void clear_desc();
  const std::string& desc() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_desc(ArgT0&& arg0, ArgT... args);
  std::string* mutable_desc();
  PROTOBUF_NODISCARD std::string* release_desc();
  void set_allocated_desc(std::string* desc);
  private:
  const std::string& _internal_desc() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_desc(const std::string& value);
  std::string* _internal_mutable_desc();
  public:

  // required uint32 code = 1;
  bool has_code() const;
  private:
  bool _internal_has_code() const;
  public:
  void clear_code();
  uint32_t code() const;
  void set_code(uint32_t value);
  private:
  uint32_t _internal_code() const;
  void _internal_set_code(uint32_t value);
  public:

  // required uint32 icode = 2;
  bool has_icode() const;
  private:
  bool _internal_has_icode() const;
  public:
  void clear_icode();
  uint32_t icode() const;
  void set_icode(uint32_t value);
  private:
  uint32_t _internal_icode() const;
  void _internal_set_icode(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:bike.mobile_code_response)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr desc_;
    uint32_t code_;
    uint32_t icode_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fbike_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// mobile_code_request

// required string mobile = 1;
inline bool mobile_code_request::_internal_has_mobile() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool mobile_code_request::has_mobile() const {
  return _internal_has_mobile();
}
inline void mobile_code_request::clear_mobile() {
  _impl_.mobile_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& mobile_code_request::mobile() const {
  // @@protoc_insertion_point(field_get:bike.mobile_code_request.mobile)
  return _internal_mobile();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void mobile_code_request::set_mobile(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.mobile_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bike.mobile_code_request.mobile)
}
inline std::string* mobile_code_request::mutable_mobile() {
  std::string* _s = _internal_mutable_mobile();
  // @@protoc_insertion_point(field_mutable:bike.mobile_code_request.mobile)
  return _s;
}
inline const std::string& mobile_code_request::_internal_mobile() const {
  return _impl_.mobile_.Get();
}
inline void mobile_code_request::_internal_set_mobile(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.mobile_.Set(value, GetArenaForAllocation());
}
inline std::string* mobile_code_request::_internal_mutable_mobile() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.mobile_.Mutable(GetArenaForAllocation());
}
inline std::string* mobile_code_request::release_mobile() {
  // @@protoc_insertion_point(field_release:bike.mobile_code_request.mobile)
  if (!_internal_has_mobile()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.mobile_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.mobile_.IsDefault()) {
    _impl_.mobile_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void mobile_code_request::set_allocated_mobile(std::string* mobile) {
  if (mobile != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.mobile_.SetAllocated(mobile, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.mobile_.IsDefault()) {
    _impl_.mobile_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bike.mobile_code_request.mobile)
}

// -------------------------------------------------------------------

// mobile_code_response

// required uint32 code = 1;
inline bool mobile_code_response::_internal_has_code() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool mobile_code_response::has_code() const {
  return _internal_has_code();
}
inline void mobile_code_response::clear_code() {
  _impl_.code_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t mobile_code_response::_internal_code() const {
  return _impl_.code_;
}
inline uint32_t mobile_code_response::code() const {
  // @@protoc_insertion_point(field_get:bike.mobile_code_response.code)
  return _internal_code();
}
inline void mobile_code_response::_internal_set_code(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.code_ = value;
}
inline void mobile_code_response::set_code(uint32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:bike.mobile_code_response.code)
}

// required uint32 icode = 2;
inline bool mobile_code_response::_internal_has_icode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool mobile_code_response::has_icode() const {
  return _internal_has_icode();
}
inline void mobile_code_response::clear_icode() {
  _impl_.icode_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint32_t mobile_code_response::_internal_icode() const {
  return _impl_.icode_;
}
inline uint32_t mobile_code_response::icode() const {
  // @@protoc_insertion_point(field_get:bike.mobile_code_response.icode)
  return _internal_icode();
}
inline void mobile_code_response::_internal_set_icode(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.icode_ = value;
}
inline void mobile_code_response::set_icode(uint32_t value) {
  _internal_set_icode(value);
  // @@protoc_insertion_point(field_set:bike.mobile_code_response.icode)
}

// optional string desc = 3;
inline bool mobile_code_response::_internal_has_desc() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool mobile_code_response::has_desc() const {
  return _internal_has_desc();
}
inline void mobile_code_response::clear_desc() {
  _impl_.desc_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& mobile_code_response::desc() const {
  // @@protoc_insertion_point(field_get:bike.mobile_code_response.desc)
  return _internal_desc();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void mobile_code_response::set_desc(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.desc_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bike.mobile_code_response.desc)
}
inline std::string* mobile_code_response::mutable_desc() {
  std::string* _s = _internal_mutable_desc();
  // @@protoc_insertion_point(field_mutable:bike.mobile_code_response.desc)
  return _s;
}
inline const std::string& mobile_code_response::_internal_desc() const {
  return _impl_.desc_.Get();
}
inline void mobile_code_response::_internal_set_desc(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.desc_.Set(value, GetArenaForAllocation());
}
inline std::string* mobile_code_response::_internal_mutable_desc() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.desc_.Mutable(GetArenaForAllocation());
}
inline std::string* mobile_code_response::release_desc() {
  // @@protoc_insertion_point(field_release:bike.mobile_code_response.desc)
  if (!_internal_has_desc()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.desc_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.desc_.IsDefault()) {
    _impl_.desc_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void mobile_code_response::set_allocated_desc(std::string* desc) {
  if (desc != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.desc_.SetAllocated(desc, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.desc_.IsDefault()) {
    _impl_.desc_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bike.mobile_code_response.desc)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace bike

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fbike_2eproto
